/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

/**
 *
 * @author joaqu
 */
public class frmHome extends javax.swing.JFrame {

    /**
     * Creates new form frmHome
     */
    public frmHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        panelOptions = new javax.swing.JPanel();
        txtResultMass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtResultMass1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtResultMass2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtResultMass5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtResultMass7 = new javax.swing.JTextField();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        panelOptions1 = new javax.swing.JPanel();
        txtResultMass8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtResultMass9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtResultMass10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtResultMass13 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtResultMass15 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtResultMass30 = new javax.swing.JTextField();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        panelOptions2 = new javax.swing.JPanel();
        txtResultMass16 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtResultMass17 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtResultMass18 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtResultMass19 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtResultMass20 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtResultMass22 = new javax.swing.JTextField();
        jSpinner3 = new javax.swing.JSpinner();
        txtResultMass23 = new javax.swing.JTextField();
        txtResultMass24 = new javax.swing.JTextField();
        panelOptions3 = new javax.swing.JPanel();
        txtResultMass11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtResultMass25 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtResultMass26 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtResultMass27 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtResultMass29 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtResultMass31 = new javax.swing.JTextField();
        jSpinner4 = new javax.swing.JSpinner();
        panelOptions4 = new javax.swing.JPanel();
        txtResultMass21 = new javax.swing.JTextField();
        txtResultMass32 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtResultMass33 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtResultMass34 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtResultMass35 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtResultMass37 = new javax.swing.JTextField();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel60 = new javax.swing.JLabel();
        panelOptions5 = new javax.swing.JPanel();
        txtResultMass28 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtResultMass38 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtResultMass39 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtResultMass40 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtResultMass41 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtResultMass42 = new javax.swing.JTextField();
        txtResultMass36 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jSpinner8 = new javax.swing.JSpinner();
        panelOptions6 = new javax.swing.JPanel();
        txtResultMass43 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        txtResultMass44 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtResultMass45 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtResultMass47 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        txtResultMass48 = new javax.swing.JTextField();
        jSpinner7 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        panelOptions7 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton11 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setAutoscrolls(true);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOptions.setBackground(new java.awt.Color(51, 51, 51));
        panelOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MEMORIA RAM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 24), new java.awt.Color(255, 255, 135))); // NOI18N
        panelOptions.setForeground(new java.awt.Color(107, 107, 107));
        panelOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultMass.setEditable(false);
        txtResultMass.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultMass.setText("1AAB");
        txtResultMass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        txtResultMass.setEnabled(false);
        panelOptions.add(txtResultMass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(142, 205, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ID Memoria:");
        panelOptions.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtResultMass1.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass1.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass1.setText(" En US$");
        txtResultMass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions.add(txtResultMass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 20));

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(142, 205, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Precio:");
        panelOptions.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtResultMass2.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass2.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass2.setText(" Memoria RAM");
        txtResultMass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions.add(txtResultMass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 20));

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(142, 205, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Descripcion:");
        panelOptions.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(142, 205, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Frecuencia:");
        panelOptions.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(142, 205, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Capacidad:");
        panelOptions.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(142, 205, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(" Modelo:");
        panelOptions.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 190, 70, -1));

        txtResultMass5.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass5.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass5.setText(" Ejemplo: X370M-VV");
        txtResultMass5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions.add(txtResultMass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, 20));

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(142, 205, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Tecnologia:");
        panelOptions.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(142, 205, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Marca:");
        panelOptions.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        txtResultMass7.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass7.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass7.setText(" Ejemplo: AORUS");
        txtResultMass7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions.add(txtResultMass7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, 20));

        jSpinner9.setModel(new javax.swing.SpinnerListModel(new String[] {"1600 MHz", "1866 MHz", "2400 MHz", "2666 MHz", "3000 MHz"}));
        panelOptions.add(jSpinner9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));

        jSpinner10.setModel(new javax.swing.SpinnerListModel(new String[] {"4 GB", "8 GB", "16 GB"}));
        panelOptions.add(jSpinner10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(100, 100, 199, 1));
        panelOptions.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, -1));

        jSpinner6.setModel(new javax.swing.SpinnerListModel(new String[] {"DDR3", "DDR4"}));
        panelOptions.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, -1));

        jPanel3.add(panelOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 308, 241));

        panelOptions1.setBackground(new java.awt.Color(51, 51, 51));
        panelOptions1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALMACENAMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 24), new java.awt.Color(255, 255, 135))); // NOI18N
        panelOptions1.setForeground(new java.awt.Color(107, 107, 107));
        panelOptions1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultMass8.setEditable(false);
        txtResultMass8.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass8.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultMass8.setText("2ABD");
        txtResultMass8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        txtResultMass8.setEnabled(false);
        panelOptions1.add(txtResultMass8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(142, 205, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ID Almacenamiento:");
        panelOptions1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtResultMass9.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass9.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass9.setText(" En US$");
        txtResultMass9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions1.add(txtResultMass9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 20));

        jLabel16.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(142, 205, 153));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Precio:");
        panelOptions1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtResultMass10.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass10.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass10.setText(" Disco Duro");
        txtResultMass10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions1.add(txtResultMass10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 20));

        jLabel17.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(142, 205, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Descripcion:");
        panelOptions1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(142, 205, 153));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Capacidad:");
        panelOptions1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(142, 205, 153));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(" Modelo:");
        panelOptions1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtResultMass13.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass13.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass13.setText(" Ejemplo: WD7200-A");
        txtResultMass13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions1.add(txtResultMass13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, -1));

        jLabel21.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(142, 205, 153));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Tecnologia:");
        panelOptions1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel22.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(142, 205, 153));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Marca:");
        panelOptions1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txtResultMass15.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass15.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass15.setText(" Ejemplo: WD");
        txtResultMass15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions1.add(txtResultMass15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 110, 20));

        jLabel35.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(142, 205, 153));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Marca:");
        panelOptions1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txtResultMass30.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass30.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions1.add(txtResultMass30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 110, -1));

        jSpinner11.setModel(new javax.swing.SpinnerNumberModel(200, 200, 299, 1));
        panelOptions1.add(jSpinner11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, -1));

        jSpinner2.setModel(new javax.swing.SpinnerListModel(new String[] {"160 GB", "260 GB", "360 GB", "500 GB", "1000 GB", "2000 GB", "4000 GB"}));
        panelOptions1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, -1));

        jSpinner12.setModel(new javax.swing.SpinnerListModel(new String[] {"HDD", "SSD", "M2", "EXT"}));
        panelOptions1.add(jSpinner12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, -1));

        jPanel3.add(panelOptions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 25, 306, 241));

        panelOptions2.setBackground(new java.awt.Color(51, 51, 51));
        panelOptions2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GABINETE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 24), new java.awt.Color(255, 255, 135))); // NOI18N
        panelOptions2.setForeground(new java.awt.Color(107, 107, 107));
        panelOptions2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultMass16.setEditable(false);
        txtResultMass16.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass16.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultMass16.setText("6ULD");
        txtResultMass16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        txtResultMass16.setEnabled(false);
        panelOptions2.add(txtResultMass16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        jLabel23.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(142, 205, 153));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("ID Gabinete:");
        panelOptions2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtResultMass17.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass17.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions2.add(txtResultMass17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, -1));

        jLabel24.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(142, 205, 153));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Precio:");
        panelOptions2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtResultMass18.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass18.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions2.add(txtResultMass18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(142, 205, 153));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Descripcion:");
        panelOptions2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel26.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(142, 205, 153));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Tamaño mm:");
        panelOptions2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        txtResultMass19.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass19.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions2.add(txtResultMass19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 30, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(142, 205, 153));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText(" Modelo:");
        panelOptions2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txtResultMass20.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass20.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions2.add(txtResultMass20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 110, -1));

        jLabel29.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(142, 205, 153));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Marca:");
        panelOptions2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        txtResultMass22.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass22.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions2.add(txtResultMass22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, -1));

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(500, 500, 599, 1));
        panelOptions2.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 20));

        txtResultMass23.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass23.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions2.add(txtResultMass23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 30, -1));

        txtResultMass24.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass24.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions2.add(txtResultMass24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 30, -1));

        jPanel3.add(panelOptions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 274, 306, 234));

        panelOptions3.setBackground(new java.awt.Color(51, 51, 51));
        panelOptions3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FUENTE DE PODER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 24), new java.awt.Color(255, 255, 135))); // NOI18N
        panelOptions3.setForeground(new java.awt.Color(107, 107, 107));
        panelOptions3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultMass11.setEditable(false);
        txtResultMass11.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass11.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultMass11.setText("4ASD");
        txtResultMass11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        txtResultMass11.setEnabled(false);
        panelOptions3.add(txtResultMass11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        jLabel18.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(142, 205, 153));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("ID Fuente:");
        panelOptions3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtResultMass25.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass25.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions3.add(txtResultMass25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, -1));

        jLabel30.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(142, 205, 153));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Precio:");
        panelOptions3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtResultMass26.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass26.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions3.add(txtResultMass26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        jLabel31.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(142, 205, 153));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Descripcion:");
        panelOptions3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel32.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(142, 205, 153));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Watts:");
        panelOptions3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        txtResultMass27.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass27.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions3.add(txtResultMass27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));

        jLabel34.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(142, 205, 153));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText(" Modelo:");
        panelOptions3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        txtResultMass29.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass29.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions3.add(txtResultMass29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, -1));

        jLabel36.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(142, 205, 153));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Marca:");
        panelOptions3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        txtResultMass31.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass31.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions3.add(txtResultMass31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(600, 600, 699, 1));
        panelOptions3.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 20));

        jPanel3.add(panelOptions3, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 274, 308, 234));

        panelOptions4.setBackground(new java.awt.Color(51, 51, 51));
        panelOptions4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GPU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 24), new java.awt.Color(255, 255, 135))); // NOI18N
        panelOptions4.setForeground(new java.awt.Color(107, 107, 107));
        panelOptions4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultMass21.setEditable(false);
        txtResultMass21.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass21.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultMass21.setText("5GDA");
        txtResultMass21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        txtResultMass21.setEnabled(false);
        panelOptions4.add(txtResultMass21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        txtResultMass32.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass32.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions4.add(txtResultMass32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, -1));

        jLabel37.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(142, 205, 153));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Precio:");
        panelOptions4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtResultMass33.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass33.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions4.add(txtResultMass33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        jLabel38.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(142, 205, 153));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Descripcion:");
        panelOptions4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel39.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(142, 205, 153));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Capacidad:");
        panelOptions4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        txtResultMass34.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass34.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions4.add(txtResultMass34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, -1));

        jLabel40.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(142, 205, 153));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText(" Modelo:");
        panelOptions4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txtResultMass35.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass35.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions4.add(txtResultMass35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 110, -1));

        jLabel42.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(142, 205, 153));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Marca:");
        panelOptions4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        txtResultMass37.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass37.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions4.add(txtResultMass37, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, -1));

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(700, 700, 799, 1));
        panelOptions4.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 20));

        jLabel60.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(142, 205, 153));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("ID GPU:");
        panelOptions4.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel3.add(panelOptions4, new org.netbeans.lib.awtextra.AbsoluteConstraints(954, 514, 306, 275));

        panelOptions5.setBackground(new java.awt.Color(51, 51, 51));
        panelOptions5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 24), new java.awt.Color(255, 255, 135))); // NOI18N
        panelOptions5.setForeground(new java.awt.Color(107, 107, 107));
        panelOptions5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultMass28.setEditable(false);
        txtResultMass28.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass28.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultMass28.setText("3AFR");
        txtResultMass28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        txtResultMass28.setEnabled(false);
        panelOptions5.add(txtResultMass28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        jLabel33.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(142, 205, 153));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("ID GPU:");
        panelOptions5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtResultMass38.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass38.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions5.add(txtResultMass38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 20));

        jLabel43.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(142, 205, 153));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Precio:");
        panelOptions5.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtResultMass39.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass39.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions5.add(txtResultMass39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 20));

        jLabel44.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(142, 205, 153));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Descripcion:");
        panelOptions5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel45.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(142, 205, 153));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Cantidad Nucleos:");
        panelOptions5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        txtResultMass40.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass40.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions5.add(txtResultMass40, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, 20));

        jLabel46.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(142, 205, 153));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText(" Modelo:");
        panelOptions5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txtResultMass41.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass41.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions5.add(txtResultMass41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 110, 20));

        jLabel47.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(142, 205, 153));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Frecuencia");
        panelOptions5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        txtResultMass42.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass42.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions5.add(txtResultMass42, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 110, 20));

        txtResultMass36.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass36.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions5.add(txtResultMass36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, -1));

        jLabel41.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(142, 205, 153));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Marca:");
        panelOptions5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jSpinner8.setModel(new javax.swing.SpinnerNumberModel(300, 300, 399, 1));
        panelOptions5.add(jSpinner8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, -1));

        jPanel3.add(panelOptions5, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 25, 306, 243));

        panelOptions6.setBackground(new java.awt.Color(51, 51, 51));
        panelOptions6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOTHERBOARD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 24), new java.awt.Color(255, 255, 135))); // NOI18N
        panelOptions6.setForeground(new java.awt.Color(107, 107, 107));
        panelOptions6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultMass43.setEditable(false);
        txtResultMass43.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass43.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultMass43.setText("7TTF");
        txtResultMass43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        txtResultMass43.setEnabled(false);
        panelOptions6.add(txtResultMass43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        jLabel48.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(142, 205, 153));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("ID Motherboard:");
        panelOptions6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtResultMass44.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass44.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions6.add(txtResultMass44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 20));

        jLabel49.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(142, 205, 153));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Precio:");
        panelOptions6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtResultMass45.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass45.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions6.add(txtResultMass45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 20));

        jLabel50.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(142, 205, 153));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Descripcion:");
        panelOptions6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel51.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(142, 205, 153));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("RGB:");
        panelOptions6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel52.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(142, 205, 153));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText(" Modelo:");
        panelOptions6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        txtResultMass47.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass47.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions6.add(txtResultMass47, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, 20));

        jLabel53.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(142, 205, 153));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Marca:");
        panelOptions6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        txtResultMass48.setBackground(new java.awt.Color(51, 51, 51));
        txtResultMass48.setForeground(new java.awt.Color(255, 255, 255));
        txtResultMass48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(142, 205, 153), 2));
        panelOptions6.add(txtResultMass48, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, 20));

        jSpinner7.setModel(new javax.swing.SpinnerNumberModel(400, 400, 499, 1));
        panelOptions6.add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 50, 20));

        jCheckBox1.setBackground(new java.awt.Color(51, 51, 51));
        jCheckBox1.setForeground(new java.awt.Color(142, 205, 153));
        jCheckBox1.setText(" ¿ Posee RGB ?");
        panelOptions6.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));

        jPanel3.add(panelOptions6, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 25, 308, 243));

        panelOptions7.setBackground(new java.awt.Color(51, 51, 51));
        panelOptions7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONFIGURACION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 24), new java.awt.Color(255, 255, 135))); // NOI18N
        panelOptions7.setForeground(new java.awt.Color(107, 107, 107));
        panelOptions7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 135));
        jRadioButton1.setText("Almacenamiento");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptions7.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 20));

        jRadioButton2.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 135));
        jRadioButton2.setText("Memoria RAM");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptions7.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 20));

        jRadioButton3.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 135));
        jRadioButton3.setText("CPU");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptions7.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 20));

        jRadioButton4.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 135));
        jRadioButton4.setText("Fuente de Poder");
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptions7.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 20));

        jRadioButton5.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 135));
        jRadioButton5.setText("GPU");
        jRadioButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptions7.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 20));

        jRadioButton6.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 135));
        jRadioButton6.setText("Gabinete");
        jRadioButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptions7.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 20));

        jRadioButton7.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 135));
        jRadioButton7.setText("Motherboard");
        jRadioButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOptions7.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, 20));

        jLabel28.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(142, 205, 153));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("GESTIONAR");
        panelOptions7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 130, -1));

        jLabel54.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(142, 205, 153));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("CARGAR ");
        panelOptions7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modify_selected0_32.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setDefaultCapable(false);
        jButton8.setFocusPainted(false);
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modify_selected1_32.png"))); // NOI18N
        jButton8.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modify_selected0_32.png"))); // NOI18N
        jButton8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modify_selected0_32.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelOptions7.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 180, 40));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/broom_selected0.png"))); // NOI18N
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setDefaultCapable(false);
        jButton9.setFocusPainted(false);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/broom_selected1.png"))); // NOI18N
        jButton9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/broom_selected0.png"))); // NOI18N
        jButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/broom_selected0.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelOptions7.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 170, 160));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_selected0.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setDefaultCapable(false);
        jButton10.setFocusPainted(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_selected1_32.png"))); // NOI18N
        jButton10.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_selected0.png"))); // NOI18N
        jButton10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_selected0.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        panelOptions7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 180, 40));

        jSeparator1.setBackground(new java.awt.Color(142, 205, 153));
        jSeparator1.setForeground(new java.awt.Color(142, 205, 153));
        panelOptions7.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 10));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_selected0_32.png"))); // NOI18N
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setDefaultCapable(false);
        jButton11.setFocusPainted(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_selected1_32.png"))); // NOI18N
        jButton11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_selected0_32.png"))); // NOI18N
        jButton11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add_selected0_32.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        panelOptions7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 180, 40));

        jSeparator3.setBackground(new java.awt.Color(142, 205, 153));
        jSeparator3.setForeground(new java.awt.Color(142, 205, 153));
        panelOptions7.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 180, 10));

        jSeparator4.setBackground(new java.awt.Color(142, 205, 153));
        jSeparator4.setForeground(new java.awt.Color(142, 205, 153));
        panelOptions7.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 370, 10));

        jSeparator5.setBackground(new java.awt.Color(142, 205, 153));
        jSeparator5.setForeground(new java.awt.Color(142, 205, 153));
        panelOptions7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 180, 10));

        jSeparator2.setBackground(new java.awt.Color(142, 205, 153));
        jSeparator2.setForeground(new java.awt.Color(142, 205, 153));
        panelOptions7.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, 10));

        jPanel3.add(panelOptions7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 274, 618, 234));

        jTable3.setBackground(new java.awt.Color(51, 51, 51));
        jTable3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 11)); // NOI18N
        jTable3.setForeground(new java.awt.Color(255, 255, 135));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(142, 205, 153));
        jTable3.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTable3.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 514, 928, 275));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 950, 790));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 840));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 0, 960, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel panelOptions;
    private javax.swing.JPanel panelOptions1;
    private javax.swing.JPanel panelOptions2;
    private javax.swing.JPanel panelOptions3;
    private javax.swing.JPanel panelOptions4;
    private javax.swing.JPanel panelOptions5;
    private javax.swing.JPanel panelOptions6;
    private javax.swing.JPanel panelOptions7;
    private javax.swing.JTextField txtResultMass;
    private javax.swing.JTextField txtResultMass1;
    private javax.swing.JTextField txtResultMass10;
    private javax.swing.JTextField txtResultMass11;
    private javax.swing.JTextField txtResultMass13;
    private javax.swing.JTextField txtResultMass15;
    private javax.swing.JTextField txtResultMass16;
    private javax.swing.JTextField txtResultMass17;
    private javax.swing.JTextField txtResultMass18;
    private javax.swing.JTextField txtResultMass19;
    private javax.swing.JTextField txtResultMass2;
    private javax.swing.JTextField txtResultMass20;
    private javax.swing.JTextField txtResultMass21;
    private javax.swing.JTextField txtResultMass22;
    private javax.swing.JTextField txtResultMass23;
    private javax.swing.JTextField txtResultMass24;
    private javax.swing.JTextField txtResultMass25;
    private javax.swing.JTextField txtResultMass26;
    private javax.swing.JTextField txtResultMass27;
    private javax.swing.JTextField txtResultMass28;
    private javax.swing.JTextField txtResultMass29;
    private javax.swing.JTextField txtResultMass30;
    private javax.swing.JTextField txtResultMass31;
    private javax.swing.JTextField txtResultMass32;
    private javax.swing.JTextField txtResultMass33;
    private javax.swing.JTextField txtResultMass34;
    private javax.swing.JTextField txtResultMass35;
    private javax.swing.JTextField txtResultMass36;
    private javax.swing.JTextField txtResultMass37;
    private javax.swing.JTextField txtResultMass38;
    private javax.swing.JTextField txtResultMass39;
    private javax.swing.JTextField txtResultMass40;
    private javax.swing.JTextField txtResultMass41;
    private javax.swing.JTextField txtResultMass42;
    private javax.swing.JTextField txtResultMass43;
    private javax.swing.JTextField txtResultMass44;
    private javax.swing.JTextField txtResultMass45;
    private javax.swing.JTextField txtResultMass47;
    private javax.swing.JTextField txtResultMass48;
    private javax.swing.JTextField txtResultMass5;
    private javax.swing.JTextField txtResultMass7;
    private javax.swing.JTextField txtResultMass8;
    private javax.swing.JTextField txtResultMass9;
    // End of variables declaration//GEN-END:variables
}
